Numpy = Numerical Python

shape (no. of rows, no. of columns) --> (2, 3) means 2 rows and 3 columns

for 1D array, shape will be (5,) means 5 elements in the array

In [3]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr)) # type of the array
print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array
print(arr.size) # number of elements in the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [13]:
## example of 3d array
# shape = (m, n, p) means m blocks, each block has n rows and p columns
arr = np.array([
        [
            [1, 2, 3, 5], 
            [4, 5, 6, 6]
        ], 
        [
            [7, 8, 9, 9], 
            [10, 11, 12, 12]
        ],
        [
            [7, 8, 9, 9], 
            [10, 11, 12, 12]
        ]
    ])
# print(arr)
print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array

3
(3, 2, 4)


In [ ]:
# 4d array
# shape = (m, n, p, q) means m blocks, each block has n blocks and each n block has p rows and q columns
arr = np.array([
        [
            [
                [1, 2, 3, 5], 
                [4, 5, 6, 6]
            ], 
            [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ],
                        [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ]
        ],
        [
            [
                [1, 2, 3, 5], 
                [4, 5, 6, 6]
            ], 
            [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ],
                        [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ]
        ],
        [
            [
                [1, 2, 3, 5], 
                [4, 5, 6, 6]
            ], 
            [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ],
                        [
                [7, 8, 9, 9], 
                [10, 11, 12, 12]
            ]
        ]
    ])

print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array

4
(3, 3, 2, 4)


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array
print(arr.size) # number of elements in the array
print(arr.dtype) # data type of the array
print(arr.itemsize) # size of each element in bytes
print(arr.nbytes) # total size of the array in bytes

2
(2, 3)
6
int64
8
48


In [32]:
#nd array generation

# random array
arr1 = np.random.rand(5)
print(arr1)

# random integer array
arr2 = np.random.randint(1, 10, size=(3, 4))
print(arr2)

# random 2d array
arr3 = np.random.rand(2, 3)
print(arr3)

[0.67472331 0.826108   0.97861904 0.08136075 0.52348664]
[[4 3 7 4]
 [6 5 6 6]
 [9 1 2 2]]
[[0.6976776  0.90985347 0.96669799]
 [0.83572953 0.95112137 0.50632553]]


In [36]:
np.random.seed(40)
arr4 = np.random.randint(1, 100, size=(2, 3))
print(arr4)

[[71 92  8]
 [38 57 51]]


In [43]:
# nd array creation from range
arr5 = np.arange(1, 10, 2) # start, stop, step
arr6 = np.arange(1, 10) # start, stop
print(arr5)
print(arr6)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


In [46]:
arr = np.linspace(1, 10, 5) # start, stop, number of elements
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [48]:
# Special arrays
zeros = np.zeros((2, 3)) # shape of the array
print("end=zeros)")
print(zeros)

ones = np.ones((3, 3)) # shape of the array
print("end=ones)")
print(ones)

end=zeros)
[[0. 0. 0.]
 [0. 0. 0.]]
end=ones)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
arr = np.full((2, 3), 7) # shape of the array, fill value
print("end=full)")
print(arr)

end=full)
[[7 7 7]
 [7 7 7]]


In [51]:
arr = np.eye(3) # identity matrix of size 3x3
print("end=eye)")
print(arr)

end=eye)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
arr = np.diag([1, 2, 3]) # diagonal array with given values
print("end=diag)")
print(arr)

end=diag)
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [53]:
# Indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0]) # first row
print(arr[1]) # second row
print(arr[2]) # third row

print(arr[0, 0]) # first element of first row
print(arr[1, 1]) # second element of second row
print(arr[2, 2]) # third element of third row

[1 2 3]
[4 5 6]
[7 8 9]
1
5
9


In [54]:
# slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0:2]) # first two rows

[[1 2 3]
 [4 5 6]]


In [58]:
# Mini Project: Student Result Analysis

import numpy as np

marks = np.array([
    [85, 90, 78], 
    [92, 88, 95], 
    [80, 85, 82],
    [78, 80, 85]
])

students = ["Alice", "Bob", "Charlie", "David"]
subjects = ["Math", "Science", "English"]

# Calculate total marks for each student
total_marks = np.sum(marks, axis=1)

print("Total Marks for each student:")
for i in range(len(students)):
    print(f"{students[i]}: {total_marks[i]}")

# Calculate average marks for each subject
average_marks = np.mean(marks, axis=0)
print("\nAverage Marks for each subject:")
for i in range(len(subjects)):
    print(f"{subjects[i]}: {average_marks[i]:.2f}")

# Find the student with the highest total marks
highest_total_index = np.argmax(total_marks)
print(f"\nStudent with the highest total marks: {students[highest_total_index]}")

# Find the subject with the lowest average marks
lowest_average_index = np.argmin(average_marks)
print(f"Subject with the lowest average marks: {subjects[lowest_average_index]}")

# pass of fail based on average marks
pass_fail = np.where(average_marks >= 80, "Pass", "Fail")
print("\nPass/Fail status for each subject:")
for i in range(len(subjects)):
    print(f"{subjects[i]}: {pass_fail[i]}")

# prercentage of marks for each student
percentage = (total_marks / 300) * 100
print("\nPercentage of marks for each student:")
for i in range(len(students)):
    print(f"{students[i]}: {percentage[i]:.2f}%")

Total Marks for each student:
Alice: 253
Bob: 275
Charlie: 247
David: 243

Average Marks for each subject:
Math: 83.75
Science: 85.75
English: 85.00

Student with the highest total marks: Bob
Subject with the lowest average marks: Math

Pass/Fail status for each subject:
Math: Pass
Science: Pass
English: Pass

Percentage of marks for each student:
Alice: 84.33%
Bob: 91.67%
Charlie: 82.33%
David: 81.00%
