In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

print("Array:", array)
print(array[-1])  # Accessing the last element
print(array[1:4])  # Slicing the array from index 1 to 3
print(array[2::2])  # Slicing the array with a step of 2

Array: [1 2 3 4 5 6]
6
[2 3 4]
[3 5]


In [ ]:
# two dimensional array
two_d_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print("Two-dimensional array:\n", two_d_array)

# Accessing elements in a two-dimensional array
print("Element at row 1, column 2:", two_d_array[1, 2])

# Slicing a two-dimensional array
print("First row:", two_d_array[0, :])
print("Second column:", two_d_array[:, 1])
print("Submatrix (rows 1-2, columns 0-1):", two_d_array[1:3, 0:2])

Two-dimensional array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix (rows 1-2, columns 0-1): [[4 5]
 [7 8]]
