In [41]:
import numpy as np
array = [2, 3, 4, 5, 6]

numpy_array = np.array(array)

print(array)
print(numpy_array)

print(type(array))
print(type(numpy_array))

[2, 3, 4, 5, 6]
[2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [42]:
numbers = [1, 2, 3, 4, 5]

print(numbers * 2)

print(np.array(numbers) * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [43]:
# Dimensions

scalar = np.array(10) # 0D array
vector = np.array([1, 2, 3, 4, 5]) # 1D array
matrix = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
) # 2D array
tensor = np.array(
    [
        [
            [1, 2], 
            [3, 4]
        ], 
        [
            [5, 6], 
            [7, 8]
        ]
    ]
) # 3D array

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("Tensor:", tensor)

Scalar: 10
Vector: [1 2 3 4 5]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# important attributes
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array)
print("Shape:", array.shape)
print("Number of dimensions:", array.ndim)
print("Size:", array.size)
print("Data type:", array.dtype)
print("Item size (in bytes):", array.itemsize)
print("Total bytes:", array.nbytes)

print("Number of rows:", array.shape[0])
print("Number of columns:", array.shape[1])

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size: 6
Data type: int64
Item size (in bytes): 8
Total bytes: 48
Number of rows: 2
Number of columns: 3


In [45]:
array = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32)
print("Array:\n", array)
print(array.dtype)


Array:
 [[1. 2. 3.]
 [4. 5. 6.]]
float32


In [46]:
float_array = np.array([1.2, 2.8, 3.5])

integer_array = float_array.astype(np.int32)

print(integer_array)

[1 2 3]


In [47]:
# array creation

array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

ones_array = np.ones((2, 3))
print("Ones Array:\n", ones_array)

filled = np.full((2, 3), 5)


print("Filled Array:\n", filled)

empty_array = np.empty((2, 3))
print("Empty Array:\n", empty_array)

identity = np.eye(3)
print("Identity Matrix:\n", identity)

diagonal = np.diag([10, 20, 30])
print("Diagonal Matrix:\n", diagonal)

arrange = np.arange(0, 10, 2)
print("Arange Array:", arrange)

linespace = np.linspace(0, 1, 5)
print("Linspace Array:", linespace)

# difference between arrange and linspace is that arange creates an array with a specified step size, while linspace creates an array with a specified number of evenly spaced values between two endpoints.

logspace = np.logspace(0, 2, 5)
print("Logspace Array:", logspace)

Array: [1 2 3 4 5]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Filled Array:
 [[5 5 5]
 [5 5 5]]
Empty Array:
 [[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
Arange Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Logspace Array: [  1.           3.16227766  10.          31.6227766  100.        ]


In [48]:
# Random numbers

rng = np.random.default_rng(seed=10)  # Create a random number generator with a seed for reproducibility
print("Random numbers from uniform distribution:", rng.random(7))

random_integers = rng.integers(low=1, high=10, size=5)
print("Random integers:", random_integers)

random_floats = rng.uniform(low=0, high=1, size=5)
print("Random floats from uniform distribution:", random_floats)

normal_distribution = rng.normal(loc=0, scale=1, size=5) # 
print("Random numbers from normal distribution:", normal_distribution)

values = rng.uniform(
    low=0,
    high=10,
    size=5
)
print("Random numbers from uniform distribution:", values)

Random numbers from uniform distribution: [0.95600171 0.20768181 0.82844489 0.14928212 0.51280462 0.1359196
 0.68903648]
Random integers: [4 8 1 4 5]
Random floats from uniform distribution: [0.82533291 0.33821531 0.57576055 0.75330186 0.82710394]
Random numbers from normal distribution: [-1.13448753  0.30570522 -1.85168503 -0.17705351  0.42582567]
Random numbers from uniform distribution: [2.26114434 8.5323975  3.06317866 9.69830368 5.17834214]


In [51]:
values = rng.normal(
    loc=0,
    scale=1,
    size=10
)

print("Random numbers from normal distribution:", values)

Random numbers from normal distribution: [-0.90538839  0.00893378 -0.40893612  0.29130385 -0.53834548  0.378475
  0.0813988   0.20453073  0.89100931 -0.78364926]


In [55]:
# Copying and viewing arrays
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
view = original_array[2:3]  # Create a view of the original array

view[0] = 99  # Modify the view

print("Original array after modifying the view:", original_array)

duplicate = original_array.copy()  # Create a copy of the original array

duplicate[0] = 100  # Modify the copy



print("Copy of the array:", duplicate)
print("Original array after modifying the copy:", original_array)



Original array after modifying the view: [ 1  2 99  4  5]
Copy of the array: [100   2  99   4   5]
Original array after modifying the copy: [ 1  2 99  4  5]


In [56]:
numbers = np.array([1, 2, 3, 4, 5])

print(np.sqrt(numbers))
print(np.square(numbers))
print(np.abs(numbers))
print(np.exp(numbers))
print(np.log(numbers))
print(np.log10(numbers))


[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [58]:
print(np.sum(numbers))
print(np.mean(numbers))
print(np.median(numbers))
print(np.min(numbers))
print(np.max(numbers))
print(np.std(numbers))
print(np.var(numbers))
print(np.percentile(numbers, 25))
print(np.quantile(numbers, 0.25))

15
3.0
3.0
1
5
1.4142135623730951
2.0
2.0
2.0


In [59]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers > 20)
print(np.any(numbers > 35))
print(np.all(numbers > 5))

condition_one = numbers >= 20
condition_two = numbers <= 30

print(np.logical_and(condition_one, condition_two))
print(np.logical_or(condition_one, condition_two))
print(np.logical_not(condition_one))
print(np.logical_xor(condition_one, condition_two))

[False False  True  True  True]
True
True
[False  True  True False False]
[ True  True  True  True  True]
[ True False False False False]
[ True False False  True  True]
